### Para obtener un frame de la camara
GET http://localhost:5000/camera


### Para obtener el JWT
POST http://localhost:5000/ HTTP/1.1
Content-Type: application/json

{
    "username": "40722571"
}

### Para verificar validez de un token

GET http://localhost:5000/verificar_token HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNjYwMDE0NCwianRpIjoiNWU3M2RjZDUtZjJlZS00MjhmLWI0YmUtZjU1MzM0ZTZmYjM1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjQwNzIyNTcxIiwibmJmIjoxNzI2NjAwMTQ0LCJjc3JmIjoiZGI5ZDQ0MTUtN2M4Zi00M2E4LTg2OTYtNjg2N2E5YTNmNjA3IiwiZXhwIjoxNzI2NjAwMjY0fQ.eIAIKi-d87MX36DA-WTjVKUCYzXslnghdCsDETOApAU



eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNjU5MjQ0MSwianRpIjoiZGY1NzM0OTYtMzQwYS00YzRjLWIxYmMtMmZiNTBlNjg2NDFiIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjQwNzIyNTcxIiwibmJmIjoxNzI2NTkyNDQxLCJjc3JmIjoiMTMzZmNkN2ItY2QxOS00OTZhLThmYzMtYmE5ZWYwMmE2YzUxIiwiZXhwIjoxNzI2NTkzNjQxfQ.xaDcbTTFdwIJUcCxYk7kOA7DOcPbbH08_glnQKevi9I